# 참고  x Json
# 1. xson_id : 전체 unique    gr+'유닉스타임'
# 2. xson_gr : 값 젇의 사용
# 3. xson_data : 자유 정의

###  X-Json Catalog 조회
GET https://apis.techux.link:5150/tux-svc2/xson/xson_list?xson_gr=eum_catalog HTTP/1.1


### X-Json Cluster 조회
GET https://apis.techux.link:5150/tux-svc2/xson/xson_list?xson_gr=eum_cluster HTTP/1.1


### X-Json Catalog 등록 (xson_id로 수정 덮어씀)

POST https://apis.techux.link:5150/tux-svc2/xson/add_xson HTTP/1.1
Content-Type: application/json
{
	"xson_id": "eum_catalog_1688013907",
	"user_id": "calvin",
	"xson_gr": "eum_catalog",
	"xson_data": { 
		"catalog_id": "1",
		"catalog_name": "asml_log_type_1",
		"created": "2023-06-29 12:10:01"
	}
}


###  X-Json Cluster 등록 (xson_id로 수정 덮어씀)
POST https://apis.techux.link:5150/tux-svc2/xson/add_xson HTTP/1.1
Content-Type: application/json

{
	"xson_id": "eum_cluster_1687981539",
	"user_id": "calvin",
	"xson_gr": "eum_cluster",
	"xson_data": { 
		"cluster_name": "Trino-Cluster-1",
		"desciption": "ASML 로그 분석을 위한 Trino Cluster11111111",
		"status": "Running",
		"enable_auto_scaling": "True",
		"created": "2023-06-01 14:56:30",
		"catalogs": [ 1, 2, 3 ],
		"cluster_size": "C",
		"initial_workers": 3,
		"coordinator_heap_size": 64,
		"worker_heap_size": 48,
		"query_memory": 32,
		"query_memory_per_worker": 24,
		"cpu_allocation_for_each_coordinator": 4,
		"cpu_allocation_for_each_worker": 4,
		"enable_auto_scaling": "True",
		"max_workers": 10,
		"cpu_utilization_threshold": 70
	}
}

###  X-Json 단건 조회 by ID
GET https://apis.techux.link:5150/tux-svc2/xson/xson_detail?xson_id=eum_cluster_1687981539 HTTP/1.1


###  X-Json 단건 삭제 by ID
POST https://apis.techux.link:5150/tux-svc2/xson/delete_xson?xson_id=eum_cluster_1688110263 HTTP/1.1


### X-Json 전체 삭제 by GR
POST https://apis.techux.link:5150/tux-svc2/xson/reset_xson?xson_gr=eum_catalog HTTP/1.1