# 참고  x Json
# 1. xson_id : 전체 unique    gr+'유닉스타임'
# 2. xson_gr : 값 젇의 사용
# 3. xson_data : 자유 정의


###  X-Json 리스트 조회 by GR
GET https://apis.techux.link:5150/tux-svc2/xson/xson_list?xson_gr=cars HTTP/1.1


###  X-Json 등록 (xson_id로 수정 덮어씀)
POST https://apis.techux.link:5150/tux-svc2/xson/add_xson HTTP/1.1
Content-Type: application/json

{
    "xson_id": "cars_0002",
    "user_id": "michael",
    "xson_gr": "cars",
    "xson_data": {
      "cars_name" :"ccccㄷㄷㄷ",
      "cars_pirce" :"start"
	}
}

###  X-Json 단건 조회 by ID
GET https://apis.techux.link:5150/tux-svc2/xson/xson_detail?xson_id=cars_0002 HTTP/1.1


###  X-Json 단건 삭제 by ID
POST https://apis.techux.link:5150/tux-svc2/xson/delete_xson?xson_id=cars_0002 HTTP/1.1


### X-Json 전체 삭제 by GR
POST https://apis.techux.link:5150/tux-svc2/xson/reset_xson?xson_gr=cars HTTP/1.1